# Generated by Django 2.2 on 2022-10-18 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190211_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='doctor_id',
        ),
    ]
